spring:
  kafka:
    consumer:
      group-id: home-service
      auto-offset-reset: earliest
      enable-auto-commit: false
    listener:
      ack-mode: manual
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username:
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  liquibase:
    change-log: classpath:liquibase/changelog.yml
server:
  port: 8081

kafka:
  bootstrap-servers: localhost:29092